
project_id = "qpcertsfswurkzcfqtpg"
[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://fit-flow-scan-track.lovable.dev"
additional_redirect_urls = ["http://localhost:5173", "http://localhost:5173/auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_email_signup = true
enable_email_autoconfirm = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
events_db_major_version = 15

[functions]
serve_flowtron = true
[functions.recipes]
verify_jwt = false
